apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 5000
      nodePort: 30001
    # - protocol: TCP
    #   port: 5001
    #   targetPort: 5000
  type: NodePort